/* Autogenerated file. Do not edit manually. */

import type { ethers, EventFilter, Signer, BigNumber, PopulatedTransaction } from 'ethers'
import type { CallOverrides } from '@ethersproject/contracts'
import { Contract } from '@ethersproject/contracts'
import type { BytesLike } from '@ethersproject/bytes'
import type { Listener, Provider } from '@ethersproject/providers'
import type { FunctionFragment, Result } from '@ethersproject/abi'

interface ISynthetixInterface extends ethers.utils.Interface {
  functions: {
    'transferableSynthetix(address)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'transferableSynthetix', values: [string]): string

  decodeFunctionResult(functionFragment: 'transferableSynthetix', data: BytesLike): Result

  events: {}
}

export class ISynthetix extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: ISynthetixInterface

  functions: {
    transferableSynthetix(
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      transferable: BigNumber
      0: BigNumber
    }>

    'transferableSynthetix(address)'(
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      transferable: BigNumber
      0: BigNumber
    }>
  }

  transferableSynthetix(account: string, overrides?: CallOverrides): Promise<BigNumber>

  'transferableSynthetix(address)'(account: string, overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    transferableSynthetix(account: string, overrides?: CallOverrides): Promise<BigNumber>

    'transferableSynthetix(address)'(account: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {}

  estimateGas: {
    transferableSynthetix(account: string, overrides?: CallOverrides): Promise<BigNumber>

    'transferableSynthetix(address)'(account: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    transferableSynthetix(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'transferableSynthetix(address)'(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
